background {
    monitor =
    color = rgb(1a1612)
}

input-field {
    monitor =
    size = 200, 40
    outline_thickness = 1
    outer_color = rgb(2e2925)
    inner_color = rgb(221e1a)
    font_color = rgb(d4c9b8)
    fade_on_empty = true
    placeholder_text = password
    check_color = rgb(8aac8a)
    fail_color = rgb(c4746e)
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(d4c9b8)
    font_size = 48
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}
