# ─────────────────────────────────────────────────────────────────────
#  「✦ HYPERPAPER CONFIG ✦ 」
# ─────────────────────────────────────────────────────────────────────

# ── WALLPAPER ────────────────────────────────────────────────────────
wallpaper {
    monitor =
    path = /home/buggy/Pictures/Wallpapers/anime-4.png
}

# ── GENERAL ──────────────────────────────────────────────────────────
splash = false
ipc = on
